PuzzleAdv.Backend/src/PuzzleAdv.Backend/Models/Puzzle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.EntityFramework;
using System.ComponentModel.DataAnnotations;


namespace PuzzleAdv.Backend.Models
{
    public class Puzzle
    {
        public int ID { get; set; }
        public string PuzzleImage { get; set; }
        public int Status { get; set; }

        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int Distance { get; set; }

        public DateTime InsertDate { get; set; }
        public DateTime? DeleteDate { get; set; }
        public DateTime? LastUpdateDate { get; set; }
        public string InsertUserId { get; set; }
        public string DeleteUserId { get; set; }
        public string LastUpdateUserId { get; set; }

        //Foreign Keys
        public int ShopId { get; set; }

        // Navigation properties
        public Shop Shop { get; set; }

    }
}

PuzzleAdv.Backend/src/PuzzleAdv.Backend/ViewModels/Puzzle/PuzzleListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using PuzzleAdv.Backend.Models;
using PuzzleAdv.Backend.Helpers;

namespace PuzzleAdv.Backend.ViewModels.Puzzle
{
    public class PuzzleListViewModel
    {
        public int ID { get; set; }

        public string IDNumber { get { return ID.ToString("D5"); } }

        public string PuzzleImage { get; set; }

        [Display(Name = "Data di inserimento")]
        [DataType(DataType.Date)]
        public DateTime InsertDate { get; set; }

        public EnumHelper.PuzzleStatus StatusEnum { get; set; }

        public string StatusInfo { get; set; }



        public static implicit operator PuzzleListViewModel(Models.Puzzle puzzle)
        {
            return new PuzzleListViewModel
            {
                ID = puzzle.ID,
                InsertDate = puzzle.InsertDate,
                PuzzleImage = puzzle.PuzzleImage,
                StatusEnum = (EnumHelper.PuzzleStatus)puzzle.Status,
                StatusInfo = StringHelper.GetStatusInfo(puzzle)
            };
        }

        public static implicit operator Models.Puzzle(PuzzleListViewModel vm)
        {
            return new Models.Puzzle
            {
                ID = vm.ID,
                InsertDate = vm.InsertDate,
                PuzzleImage = vm.PuzzleImage
            };
        }
    
    }


}

PuzzleAdv.Backend/src/PuzzleAdv.Backend/Controllers/PuzzleController.cs
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Hosting;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using PuzzleAdv.Backend.Helpers;
using PuzzleAdv.Backend.Interfaces;
using PuzzleAdv.Backend.Models;
using PuzzleAdv.Backend.ViewModels.Puzzle;
using PuzzleAdv.Backend.ViewModels.Shop;
using System;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using GoogleMaps.LocationServices;
using CodeFirstStoreFunctions;


namespace PuzzleAdv.Backend.Controllers
{
    [RequireHttps]
    public class PuzzleController : Controller
    {
        private readonly IPuzzleRepository _puzzleRepository;
        private readonly IShopRepository _shopRepository;
        private IHostingEnvironment _environment;

        public PuzzleController(IPuzzleRepository puzzleRepository, IShopRepository shopRepository, IHostingEnvironment environment)
        {
            _puzzleRepository = puzzleRepository;
            _shopRepository = shopRepository;
            _environment = environment;
        }

        // GET: Puzzle List
        public IActionResult Index()
        {
            var puzzleListVm = _puzzleRepository.GetPuzzles(User);
            return View(puzzleListVm);
        }

        // GET: Puzzle/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Puzzle/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile croppedImage1, IFormFile croppedImage2, int distance)
        {

            var uploads = Path.Combine(_environment.WebRootPath, "Uploads");

            if (croppedImage1.Length > 0 && croppedImage2.Length > 0)
            {
                var puzzleImageId = Guid.NewGuid().ToString();
                var fileName = string.Format("{0}.jpg", puzzleImageId);

                await croppedImage1.SaveAsAsync(Path.Combine(uploads, fileName));

                ImageResizer.ImageJob img1 = new ImageResizer.ImageJob(Path.Combine(uploads, fileName), Path.Combine(uploads, "16-9", "400", fileName),
                                new ImageResizer.Instructions("maxheight=400;&scale=both;format=jpg;mode=max"));

                img1.Build();

                ImageResizer.ImageJob img2 = new ImageResizer.ImageJob(Path.Combine(uploads, fileName), Path.Combine(uploads, "16-9", "1065", fileName),
                                                new ImageResizer.Instructions("maxheight=1065;&scale=both;format=jpg;mode=max"));

                img2.Build();


                if (ModelState.IsValid)
                {
                    await _puzzleRepository.AddPuzzleAsync(User, puzzleImageId, distance, _shopRepository.GetUserShop(User).ID);
                }
            }

            return View();

        }


    }
}

PuzzleAdv.Backend/src/PuzzleAdv.Backend/Views/Puzzle/Create.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Nuovo Puzzle";
}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="container">
        <div class="ibox">
            <div class="ibox-title">
                <h4>Nuovo Puzzle</h4>
            </div>
            <div class="ibox-content">

                <form id="form" asp-action="Create" method="post" class="wizard-big">
                    <h1>Raggio d'azione</h1>
                    <fieldset>
                        <h2>Entro che raggio, rispetto al tuo negozio, vorresti che venga visualizzato il puzzle?</h2>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <p></p>
                                    <input type="text" id="distance" name="distance" value="" />
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="text-center">
                                    <div style="margin-top: 20px">
                                        <i class="fa fa-map-marker" style="font-size: 150px;color: #e5e5e5 "></i>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </fieldset>
                    <h1>Immagine 16:9</h1>
                    <fieldset>
                        <h2>Configura l'immagine per schermi a 16:9</h2>
                        @Html.Partial("_ImageCropperPartial1")
                    </fieldset>

                    <h1>Immagine 4:3</h1>
                    <fieldset>
                        <h2>Configura l'immagine per schermi a 4:3</h2>
                        @Html.Partial("_ImageCropperPartial2")
                    </fieldset>

                    <h1>Priorit&aacute;</h1>
                    <fieldset>
                        <h2>Scegli il livello di priorit&aacute; da assegnare al tuo Puzzle:</h2>
                        @Html.Partial("_Premium")
                    </fieldset>

                    <h1>Termini e condizioni</h1>
                    <fieldset>
                        <h2>Termini e condizioni</h2>
                        <input id="acceptTerms" name="acceptTerms" type="checkbox" class="required"> <label for="acceptTerms">Accetto i termini e le condizioni.</label>
                    </fieldset>

                    <h1>Invio dati</h1>
                    <fieldset>
                        <h2>Invio dati in corso, attendere ...</h2>
                        <div class="sk-spinner sk-spinner-wave">
                            <div class="sk-rect1"></div>
                            <div class="sk-rect2"></div>
                            <div class="sk-rect3"></div>
                            <div class="sk-rect4"></div>
                            <div class="sk-rect5"></div>
                        </div>
                    </fieldset>
                </form>

            </div>
        </div>
    </div>
</div>


@section Styles {
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/ionRangeSlider/ion.rangeSlider.css" />
        <link rel="stylesheet" href="~/lib/ionRangeSlider/ion.rangeSlider.skinFlat.css" />
        <link rel="stylesheet" href="~/lib_bower/cropper/dist/cropper.css" />
        <link rel="stylesheet" href="~/lib/steps/jquery.steps.css" />
        <link rel="stylesheet" href="~/lib/iCheck/custom.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/ionRangeSlider/ion.rangeSlider.css" />
        <link rel="stylesheet" href="~/lib/ionRangeSlider/ion.rangeSlider.skinFlat.css" />
        <link rel="stylesheet" href="~/lib_bower/cropper/dist/cropper.css" />
        <link rel="stylesheet" href="~/lib/steps/jquery.steps.css" />
        <link rel="stylesheet" href="~/lib/iCheck/custom.css" />
    </environment>
}

@section Scripts {
    <environment names="Development">
        <script src="~/lib_bower/moment/moment.js"></script>
        <script src="~/lib/ionRangeSlider/ion.rangeSlider.min.js"></script>
        <script src="~/lib_bower/cropper/dist/cropper.js"></script>
        <script src="~/lib/blueimp-canvas-to-blob/js/canvas-to-blob.js"></script>
        <script src="~/lib/steps/jquery.steps.js"></script>
        <script src="~/lib/iCheck/icheck.min.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib_bower/moment/moment.js"></script>
        <script src="~/lib/ionRangeSlider/ion.rangeSlider.min.js"></script>
        <script src="~/lib_bower/cropper/dist/cropper.js"></script>
        <script src="~/lib/blueimp-canvas-to-blob/js/canvas-to-blob.js"></script>
        <script src="~/lib/steps/jquery.steps.js"></script>
        <script src="~/lib/iCheck/icheck.min.js"></script>
    </environment>

   
    <script type="text/javascript">


        $(document).ready(function () {

            // *** iCheck ***
            $(document).ready(function () {
                $('.i-checks').iCheck({
                    checkboxClass: 'icheckbox_square-green',
                    radioClass: 'iradio_square-green',
                });
            });

            // *** steps ***

            $("#form").steps({
                bodyTag: "fieldset",
                stepsOrientation: "vertical",
                enableFinishButton: false,
                labels: {
                    next: "Avanti",
                    previous: "Indietro",
                    loading: "Loading ..."
                },
                onStepChanging: function (event, currentIndex, newIndex) {
                    // Always allow going backward even if the current step contains invalid fields!
                    if (currentIndex > newIndex) {
                        $('a[href="#next"]').text('Avanti');
                        return true;
                    }

                    // Forbid suppressing "Warning" step if the user is to young
                    if (newIndex === 1 && $("#StartDate").val() === '') {
                        return false;
                    }

                    if (newIndex === 3) {
                        $('a[href="#next"]').text('Invia');
                    }

                    if (newIndex === 4) {

                        $('a[href="#previous"]').css('display', 'none');
                        $('a[href="#finish"]').css('display', 'none');

                        var form = $('#form');
                        var formData = new FormData(form.get(0)); //get AntiForgeryToken

                        $image1.cropper('getCroppedCanvas').toBlob(function (blob) {

                            formData.append('croppedImage1', blob);

                            $image2.cropper('getCroppedCanvas').toBlob(function (blob) {

                                formData.append('croppedImage2', blob);

                                $.ajax('/Puzzle/Create', {
                                    method: "POST",
                                    data: formData,
                                    processData: false,
                                    contentType: false,
                                    success: function () {
                                        console.log('Upload success');
                                        var url = '@Url.Action("Index", "Puzzle")';
                                        window.location.href = url;
                                    },
                                    error: function () {
                                        console.log('Upload error');
                                    }

                                });

                            });

                        });

                    }

                    return true;

                    // Start validation; Prevent going forward if false
                    //return form.valid();
                },
                onFinished: function (event, currentIndex) { }
            });


            // *** slider ***
            $("#distance").ionRangeSlider({
                postfix: "Km",
                hasGrid: true,
                min: 10,
                max: 50
            });


            // *** cropper *** --> see view _ImageCropperPartial

            var $image1 = $("#img-crop-1 > img")
            $($image1).cropper({
                aspectRatio: 0.666666667,
                preview: "#img-preview-1",
                done: function (data) {
                    // Output the result data for cropping image.
                }
            });
            var $image2 = $("#img-crop-2 > img")
            $($image2).cropper({
                aspectRatio: 0.8585858585858586,
                preview: "#img-preview-2",
                done: function (data) {
                    // Output the result data for cropping image.
                }
            });


            var $inputImage1 = $("#inputImage1");
            if (window.FileReader) {
                $inputImage1.change(function () {
                    var fileReader = new FileReader(),
                            files = this.files,
                            file;

                    if (!files.length) {
                        return;
                    }

                    file = files[0];

                    if (/^image\/\w+$/.test(file.type)) {
                        fileReader.readAsDataURL(file);
                        fileReader.onload = function () {
                            $inputImage1.val("");
                            $image1.cropper("reset", true).cropper("replace", this.result);
                        };
                    } else {
                        showMessage("Please choose an image file.");
                    }
                });
            } else {
                $inputImage.addClass("hide");
            }

            var $inputImage2 = $("#inputImage2");
            if (window.FileReader) {
                $inputImage2.change(function () {
                    var fileReader = new FileReader(),
                            files = this.files,
                            file;

                    if (!files.length) {
                        return;
                    }

                    file = files[0];

                    if (/^image\/\w+$/.test(file.type)) {
                        fileReader.readAsDataURL(file);
                        fileReader.onload = function () {
                            $inputImage2.val("");
                            $image2.cropper("reset", true).cropper("replace", this.result);
                        };
                    } else {
                        showMessage("Please choose an image file.");
                    }
                });
            } else {
                $inputImage.addClass("hide");
            }


            $("#zoomIn1").click(function () {
                $image1.cropper("zoom", 0.1);
            });

            $("#zoomOut1").click(function () {
                $image1.cropper("zoom", -0.1);
            });

            $("#moveLeft1").click(function () {
                $image1.cropper("move", -1, 0);
            });

            $("#moveRight1").click(function () {
                $image1.cropper("move", 1, 0);
            });

            $("#moveUp1").click(function () {
                $image1.cropper("move", 0, -1);
            });

            $("#moveDown1").click(function () {
                $image1.cropper("move", 0, 1);
            });

            $("#zoomIn2").click(function () {
                $image1.cropper("zoom", 0.1);
            });

            $("#zoomOut2").click(function () {
                $image2.cropper("zoom", -0.1);
            });

            $("#moveLeft2").click(function () {
                $image2.cropper("move", -1, 0);
            });

            $("#moveRight2").click(function () {
                $image2.cropper("move", 1, 0);
            });

            $("#moveUp2").click(function () {
                $image2.cropper("move", 0, -1);
            });

            $("#moveDown2").click(function () {
                $image2.cropper("move", 0, 1);
            });

        });

    </script>
}

PuzzleAdv.Backend/src/PuzzleAdv.Backend/Views/Puzzle/Index.cshtml
@model IEnumerable<PuzzleAdv.Backend.ViewModels.Puzzle.PuzzleListViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "I tuoi Puzzle";
}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="container">
        <div class="ibox">
            <div class="ibox-title">
                <h4>I tuoi Puzzle</h4>
                <div class="ibox-tools">
                    <a class="btn btn-primary" asp-action="Create">Nuovo Puzzle</a>
                </div>
            </div>
            <div class="ibox-content">
                <div class="row">

                    @foreach (var item in Model)
                    {

                        <div class="col-md-3">
                            <div class="ibox">
                                <div class="ibox-content product-box">
                                    <div class="ibox-content no-padding border-left-right">
                                        <a href="~/Uploads/16-9/1065/@(item.PuzzleImage).jpg" class="fancybox" data-fancybox-group="images_gallery">
                                            <figure class="img-hover">
                                                <img class="img-responsive" src="~/Uploads/16-9/400/@(item.PuzzleImage).jpg" alt="image" />
                                                <div class="img-hover-masked"></div>
                                            </figure>
                                        </a>
                                        <!--img alt="image" class="img-responsive" src="~/Uploads/16-9/400/.jpg">-->
                                    </div>
                                    <div class="product-desc">
                                        <small class="text-muted">#@(item.IDNumber) | @Html.DisplayFor(modelItem => item.InsertDate)</small>
                                        <a href="#" class="product-name">
                                            <i class="fa @(item.StatusEnum.DisplayIcon())"></i>
                                            @(item.StatusEnum.DisplayName())
                                        </a>
                                        <div class="small m-t-xs">
                                            @Html.Raw(item.StatusInfo)
                                        </div>
                                        <div class="m-t text-left">
                                            <a asp-action="Edit" asp-route-id="@item.ID" class="btn btn-xs btn-outline btn-primary">
                                                Gestisci <i class="fa fa-long-arrow-right"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    }

                </div>
            </div>
        </div>

    </div>
</div>


@section Styles {
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/fancybox/source/jquery.fancybox.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/fancybox/source/jquery.fancybox.css" />
    </environment>
}

@section Scripts {
    <environment names="Development">
        <script src="~/lib/fancybox/source/jquery.fancybox.pack.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/fancybox/source/jquery.fancybox.pack.js"></script>
    </environment>

    <script type="text/javascript">

        $(document).ready(function () {

            $('.fancybox').fancybox({
                loop: false
            });

        });

    </script>
}

PuzzleAdv.Backend/src/PuzzleAdv.Backend/Views/Puzzle/_ImageCropperPartial1.cshtml
<p>Usa i comandi sotto per spostare l'immagine con precisione</p>
<div class="row">
    <div class="col-md-12">
        <div class="btn-group">
            <label title="Carica immagine" for="inputImage1" class="btn btn-primary">
                <input type="file" accept="image/*" name="file" id="inputImage1" class="hide">
                Carica immagine
            </label>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-7">
        <div class="img-crop cropper-bg" id="img-crop-1">
            <img src="#" class="hidden">
        </div>
    </div>
    <div class="col-md-5">
        <div class="img-mockup img-mockup-1">
            <div class="img-preview-1 cropper-bg" id="img-preview-1"></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-7 text-center">
        <div class="btn-group">
            <p></p>
            <button class="btn btn-white" id="moveLeft1" type="button"><i class="fa fa-arrow-left"></i></button>
            <button class="btn btn-white" id="moveRight1" type="button"><i class="fa fa-arrow-right"></i></button>
            <button class="btn btn-white" id="moveUp1" type="button"><i class="fa fa-arrow-up"></i></button>
            <button class="btn btn-white" id="moveDown1" type="button"><i class="fa fa-arrow-down"></i></button>
            <button class="btn btn-white" id="zoomIn1" type="button"><i class="fa fa-search-plus"></i></button>
            <button class="btn btn-white" id="zoomOut1" type="button"><i class="fa fa-search-minus"></i></button>
        </div>
    </div>
</div>

PuzzleAdv.Backend/src/PuzzleAdv.Backend/Views/Puzzle/_ImageCropperPartial2.cshtml
<p>Usa i comandi sotto per spostare l'immagine con precisione</p>
<div class="row">
    <div class="col-md-12">
        <div class="btn-group">
            <label title="Carica immagine" for="inputImage2" class="btn btn-primary">
                <input type="file" accept="image/*" name="file" id="inputImage2" class="hide">
                Carica immagine
            </label>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-7">
        <div class="img-crop cropper-bg" id="img-crop-2">
            <img src="#" class="hidden">
        </div>
    </div>
    <div class="col-md-5">
        <div class="img-mockup img-mockup-2">
            <div class="img-preview-2 cropper-bg" id="img-preview-2"></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-7 text-center">
        <div class="btn-group">
            <p></p>
            <button class="btn btn-white" id="moveLeft2" type="button"><i class="fa fa-arrow-left"></i></button>
            <button class="btn btn-white" id="moveRight2" type="button"><i class="fa fa-arrow-right"></i></button>
            <button class="btn btn-white" id="moveUp2" type="button"><i class="fa fa-arrow-up"></i></button>
            <button class="btn btn-white" id="moveDown2" type="button"><i class="fa fa-arrow-down"></i></button>
            <button class="btn btn-white" id="zoomIn2" type="button"><i class="fa fa-search-plus"></i></button>
            <button class="btn btn-white" id="zoomOut2" type="button"><i class="fa fa-search-minus"></i></button>
        </div>
    </div>
</div>

PuzzleAdv.Backend/src/PuzzleAdv.Backend/Views/Puzzle/_Premium.cshtml
<div class="row">
    <div class="col-lg-12">
        <div class="form-group">
            <div class="col-lg-8">
                <br />
                <div class="i-checks"><label> <input type="radio" value="option1" name="a"> <i></i> priorit&aacute; normale </label></div>
                <div class="i-checks"><label> <input type="radio" value="option2" name="a"> <i></i> priorit&aacute; alta per 1 settimana </label></div>
                <div class="i-checks"><label> <input type="radio" value="option2" name="a"> <i></i> priorit&aacute; alta per 2 settimane </label></div>
                <div class="i-checks"><label> <input type="radio" value="option2" name="a"> <i></i> priorit&aacute; alta per 3 settimane </label></div>
                <div class="i-checks"><label> <input type="radio" value="option2" name="a"> <i></i> priorit&aacute; alta per 4 settimane </label></div>
                <div class="i-checks"><label> <input type="radio" value="option2" name="a"> <i></i> priorit&aacute; massima per 1 settimana </label></div>
                <div class="i-checks"><label> <input type="radio" value="option2" name="a"> <i></i> priorit&aacute; massima per 2 settimane </label></div>
            </div>
            <div class="col-lg-4">
                <br />
                <div><label> GRATIS </label></div>
                <div><label> 19 &euro; </label></div>
                <div><label> 34 &euro; </label></div>
                <div><label> 49 &euro; </label></div>
                <div><label> 62 &euro; </label></div>
                <div><label> 89 &euro; </label></div>
                <div><label> 162 &euro; </label></div>
            </div>
        </div>
    </div>
</div>